param([switch]$Check)
# Catalog-derived navigation, never a claim of correctness or test coverage.
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot 'check_inventory.ps1')
$inventory=Get-CheckInventory $root
function U([string]$hex) { -join @($hex.Split(' ') | ForEach-Object { [char][Convert]::ToInt32($_,16) }) }
function Link([string]$label,[string]$path) {
    $label=$label.Replace('|','\|').Replace('[','\[').Replace(']','\]')
    $path=$path.Replace('%','%25').Replace('#','%23').Replace(' ','%20')
    '['+$label+'](<../../'+$path+'>)'
}
$lines=New-Object 'Collections.Generic.List[string]'
$lines.Add('# '+(U '7b97 6cd5 6761 76ee'))
$lines.Add('')
$lines.Add('<!-- Generated by scripts/make_features.ps1 from the shared inventory. -->')
$lines.Add('')
$lines.Add((-join @([char]0x5b,[char]0x529f,[char]0x80fd,[char]0x603b,[char]0x89c8,[char]0x5d,[char]0x28,[char]0x52,[char]0x45,[char]0x41,[char]0x44,[char]0x4d,[char]0x45,[char]0x2e,[char]0x6d,[char]0x64,[char]0x29,[char]0x20,[char]0x7c,[char]0x20,[char]0x5b,[char]0x767b,[char]0x8bb0,[char]0x6e05,[char]0x5355,[char]0x5d,[char]0x28,[char]0x2e,[char]0x2e,[char]0x2f,[char]0x2e,[char]0x2e,[char]0x2f,[char]0x7a,[char]0x6f,[char]0x69,[char]0x2f,[char]0x5f,[char]0x63,[char]0x61,[char]0x74,[char]0x61,[char]0x6c,[char]0x6f,[char]0x67,[char]0x2e,[char]0x74,[char]0x78,[char]0x74,[char]0x29,[char]0x20,[char]0x7c,[char]0x20,[char]0x5b,[char]0x5bf9,[char]0x62cd,[char]0x8d44,[char]0x4ea7,[char]0x8868,[char]0x5d,[char]0x28,[char]0x2e,[char]0x2e,[char]0x2f,[char]0x2e,[char]0x2e,[char]0x2f,[char]0x72,[char]0x75,[char]0x6c,[char]0x65,[char]0x73,[char]0x2f,[char]0x72,[char]0x65,[char]0x6c,[char]0x69,[char]0x61,[char]0x62,[char]0x69,[char]0x6c,[char]0x69,[char]0x74,[char]0x79,[char]0x2e,[char]0x6d,[char]0x64,[char]0x29)))
$lines.Add('')
$lines.Add('`./scripts/make_features.ps1` / `./scripts/make_features.ps1 -Check`')
$entries=@($inventory.entries | Where-Object { $_.kind -ne 'exempt' })
$domains=New-Object 'Collections.Generic.List[string]'
foreach ($e in $entries) { $domain=$e.path.Split('/')[1]; if (-not $domains.Contains($domain)) { $domains.Add($domain) } }
foreach ($domain in $domains) {
    $items=@($entries | Where-Object { $_.path.Split('/')[1] -ceq $domain })
    $lines.Add(''); $lines.Add('## '+$domain); $lines.Add('')
    $lines.Add('| '+(U '6761 76ee')+' | '+(U '8df3 677f 6216 7b14 8bb0')+' |'); $lines.Add('|---|---|')
    foreach ($e in $items) {
        $parts=$e.path.Split('/'); $label=($parts[2..($parts.Length-1)] -join ' / ')
        $label=$label -replace '\.[^./]+$',''
        $kind=U '7b14 8bb0 ff08 65e0 8df3 677f ff09'
        if ($e.kind -eq 'engine') { $kind=Link ($e.name+'.h') ('zoi/'+$e.name+'.h') }
        $lines.Add('| '+(Link $label $e.path)+' | '+$kind+' |')
    }
}
$text=($lines -join "`n")+"`n"
$output=Join-Path $root 'docs/features/catalog.md'
$enc=New-Object Text.UTF8Encoding($false)
$same=[IO.File]::Exists($output) -and [IO.File]::ReadAllText($output,$enc).Replace("`r`n","`n") -ceq $text
if ($Check) {
    if (-not $same) { Write-Host '[FAIL] feature catalog is stale; run scripts/make_features.ps1'; exit 1 }
    Write-Host '[OK] feature catalog is current'; exit 0
}
if (-not $same) { [IO.File]::WriteAllText($output,$text,$enc) }
Write-Host ('[OK] feature catalog: '+$entries.Count+' catalog entries')
