param([switch]$Check)
# ASCII-only; stable UTF-8 Markdown, no timestamps or execution claims.
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot 'check_inventory.ps1')
$inventory=Get-CheckInventory $root
$lines=New-Object 'Collections.Generic.List[string]'
function Link([string]$label,[string]$path) {
    $label=$label.Replace('\','\\').Replace('|','\|').Replace('[','\[').Replace(']','\]')
    $path=$path.Replace('%','%25').Replace('#','%23').Replace(' ','%20').Replace('<','%3C').Replace('>','%3E')
    return '['+$label+'](<../'+$path+'>)'
}
$lines.Add('# Template test assets (generated)')
$lines.Add('')
$lines.Add('<!-- Generated by scripts/make_reliability.ps1; do not edit by hand. -->')
$lines.Add('')
$lines.Add('A/B/C describe static test assets, NOT confidence or correctness. A direct include (even in a conditional branch) does not prove API calls, independent oracles, or a passing run. Macro includes and transitive dependencies are not counted.')
$lines.Add('')
$lines.Add('Source: zoi/_catalog.txt and algorithms/**/*_check.cpp. Pure catalog stubs resolve to their engine; commented examples are ignored. Run results, environments and historical review notes belong in reports and [sweep history](sweep-history.md).')
$lines.Add('')
$lines.Add('Refresh: `./scripts/make_reliability.ps1`; read-only verification: `./scripts/make_reliability.ps1 -Check`. Ordinary regression runs do not rewrite this file.')
$groups=@(
    @{title='A - Catalog engines with direct test references'; entries=@($inventory.entries | Where-Object { $_.kind -eq 'engine' -and $_.suites.Count -gt 0 })},
    @{title='B - Catalog engines without direct test references (TEST GAP)'; entries=@($inventory.entries | Where-Object { $_.kind -eq 'engine' -and $_.suites.Count -eq 0 })},
    @{title='C - Catalog prose (not compiled)'; entries=@($inventory.entries | Where-Object { $_.kind -eq 'note' })},
    @{title='Exempt C++ sources (no catalog stub; not automatically prose)'; entries=@($inventory.entries | Where-Object { $_.kind -eq 'exempt' })}
)
foreach ($group in $groups) {
    $lines.Add(''); $lines.Add('## '+$group.title+' ['+$group.entries.Count+']'); $lines.Add('')
    $lines.Add('| Source | Direct test references |'); $lines.Add('|---|---|')
    foreach ($e in $group.entries) {
        $label=$e.path; if ($e.name) { $label=$e.name+' - '+$e.path }
        $refs=@($e.suites | ForEach-Object { Link $_ $_ })
        $value='none'; if ($e.kind -eq 'note') { $value='not applicable' }
        elseif ($refs.Count) { $value=$refs -join '<br>' }
        $lines.Add('| '+(Link $label $e.path)+' | '+$value+' |')
    }
}
$lines.Add(''); $lines.Add('## Discovered regression suites ['+$inventory.checks.Count+']'); $lines.Add('')
foreach ($suite in $inventory.checks) { $lines.Add('- '+(Link $suite $suite)) }
$text=($lines -join "`n")+"`n"
$enc=New-Object Text.UTF8Encoding($false)
$output=Join-Path $root 'rules/reliability.md'
$same=[IO.File]::Exists($output) -and [IO.File]::ReadAllText($output,$enc).Replace("`r`n","`n") -ceq $text
if ($Check) {
    if (-not $same) { Write-Host '[FAIL] reliability.md is stale; run scripts/make_reliability.ps1'; exit 1 }
    Write-Host '[OK] reliability.md is current'; exit 0
}
if (-not $same) { [IO.File]::WriteAllText($output,$text,$enc) }
Write-Host ('[OK] reliability.md: '+$inventory.entries.Count+' assets, '+$inventory.checks.Count+' suites')
